@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@userid = 1
##################################################
#create new user
POST http://{{host}}/createuser HTTP/1.1
content-type: application/json

{
    "username":"test1",
    "email":"test1",
    "password":"test1"
}

###get user details
GET http://{{host}}/user/{{userid}} HTTP/1.1

###update user with POST
POST http://{{host}}/user/{{userid}}  HTTP/1.1
content-type: application/json

{
    "username":"test1",
    "email":"test1@post",
    "password":"test1"
}
###update user with PUT
PUT http://{{host}}/user/{{userid}}  HTTP/1.1
content-type: application/json

{
    "email":"test1@put"
}